/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medunica;

import java.awt.Component;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


/**
 *
 * @author LEX
 */
public class Registrator extends javax.swing.JFrame {

    DataBase db = null;
    /**
     * Creates new form Registrator
     */
    public Registrator(){
        initComponents(); 
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("medunica.jpg")));
        db = new DataBase("jdbc:mysql://localhost/medunica?character_set_server=utf8mb4&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "root", "toor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPaneRegistrator = new javax.swing.JTabbedPane();
        panelGeneralInformation = new javax.swing.JPanel();
        lblPasportSeries = new javax.swing.JLabel();
        textFieldSnils = new javax.swing.JTextField();
        textFieldPasportSeries = new javax.swing.JTextField();
        lblPasportNumber = new javax.swing.JLabel();
        textFieldPasportNumber = new javax.swing.JTextField();
        lblIssuedBy = new javax.swing.JLabel();
        textFieldPermanentRegistration = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblDateOfIssue = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        textFieldIssuedBy = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblTelephone = new javax.swing.JLabel();
        textFieldTelephone = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        radioButtonGenderM = new javax.swing.JRadioButton();
        radioButtonGenderG = new javax.swing.JRadioButton();
        lblResidenceAddress = new javax.swing.JLabel();
        lblFamily = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        textFieldDateOfIssue = new javax.swing.JTextField();
        lblPermanentRegistration = new javax.swing.JLabel();
        lblPatron = new javax.swing.JLabel();
        textFieldResidenceAddress = new javax.swing.JTextField();
        textFieldFamily = new javax.swing.JTextField();
        lblIpr = new javax.swing.JLabel();
        textFieldName = new javax.swing.JTextField();
        textFieldIpr = new javax.swing.JTextField();
        textFieldPatron = new javax.swing.JTextField();
        lblIprData = new javax.swing.JLabel();
        lblDataBirth = new javax.swing.JLabel();
        textFieldIprData = new javax.swing.JTextField();
        textFieldDataBirth = new javax.swing.JTextField();
        lblSnils = new javax.swing.JLabel();
        panelSocialCharacteristic = new javax.swing.JPanel();
        lblDisabilityGroup = new javax.swing.JLabel();
        lblCauseOfDisability = new javax.swing.JLabel();
        lblDisabilityDate = new javax.swing.JLabel();
        lblPrimaryViolations = new javax.swing.JLabel();
        comboBoxDisabilityGroup = new javax.swing.JComboBox<>();
        lblRehabilitationFacilities = new javax.swing.JLabel();
        lblPlaceOfWork = new javax.swing.JLabel();
        lblWelfareLavel = new javax.swing.JLabel();
        lblEducation = new javax.swing.JLabel();
        lblMaritalStatus = new javax.swing.JLabel();
        textFieldCauseOfDisability = new javax.swing.JTextField();
        textFieldDisabilityDate = new javax.swing.JTextField();
        comboBoxRehabilitationFacilities = new javax.swing.JComboBox<>();
        textFieldPlaceOfWork = new javax.swing.JTextField();
        comboBoxWelfareLavel = new javax.swing.JComboBox<>();
        comboBoxEducation = new javax.swing.JComboBox<>();
        comboBoxMaritalStatus = new javax.swing.JComboBox<>();
        comboBoxPrimaryViolations = new javax.swing.JComboBox<>();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("МЕДУНИЦА РЕГИСТРАТОР");

        lblPasportSeries.setText("Серия паспорта");

        lblPasportNumber.setText("Номер паспорта");

        lblIssuedBy.setText("Кем выдан");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");

        lblDateOfIssue.setText("Дата выдачи");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblTelephone.setText("Телефон");

        lblEmail.setText("Эл.почта");

        lblGender.setText("Пол");

        radioButtonGenderM.setText("М");
        radioButtonGenderM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonGenderMActionPerformed(evt);
            }
        });

        radioButtonGenderG.setText("Ж");
        radioButtonGenderG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonGenderGActionPerformed(evt);
            }
        });

        lblResidenceAddress.setText("Адрес места жительства");

        lblFamily.setText("Фамилия");

        lblName.setText("Имя");

        lblPermanentRegistration.setText("Место постоянной регистрации");

        lblPatron.setText("Отчество");

        lblIpr.setText("ИПР/ИПРА");

        lblIprData.setText("Дата разработки ИПР/ИПРА");

        lblDataBirth.setText("ДатаРождения");

        lblSnils.setText("СНИЛС");

        javax.swing.GroupLayout panelGeneralInformationLayout = new javax.swing.GroupLayout(panelGeneralInformation);
        panelGeneralInformation.setLayout(panelGeneralInformationLayout);
        panelGeneralInformationLayout.setHorizontalGroup(
            panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPatron, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDataBirth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFamily, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSnils, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldSnils, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                                        .addComponent(radioButtonGenderM)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radioButtonGenderG))
                                    .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldFamily, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldDataBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldPatron, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPasportNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPasportSeries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDateOfIssue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblIssuedBy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPermanentRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblResidenceAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldPasportSeries)
                                    .addComponent(textFieldPasportNumber)
                                    .addComponent(textFieldIssuedBy)
                                    .addComponent(textFieldDateOfIssue)
                                    .addComponent(textFieldResidenceAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textFieldPermanentRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblIpr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblIprData))
                                .addGap(18, 18, 18)
                                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldIprData)
                                    .addComponent(textFieldIpr, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldTelephone)
                                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelGeneralInformationLayout.setVerticalGroup(
            panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldPasportSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPasportSeries))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldPasportNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPasportNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldIssuedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIssuedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldDateOfIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDateOfIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldResidenceAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblResidenceAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldPermanentRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPermanentRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFamily)
                            .addComponent(textFieldFamily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatron)
                            .addComponent(textFieldPatron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldDataBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataBirth))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldSnils, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSnils))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radioButtonGenderG)
                                .addComponent(radioButtonGenderM))
                            .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIpr)
                            .addComponent(textFieldIpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldIprData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIprData, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPaneRegistrator.addTab("Общие данные", panelGeneralInformation);

        lblDisabilityGroup.setText("Группа инвалидности");

        lblCauseOfDisability.setText("Причина инвалидности");

        lblDisabilityDate.setText("Дата установки инвалидности");

        lblPrimaryViolations.setText("Преимущественные нарушения");

        comboBoxDisabilityGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "нет", "1", "2", "3" }));

        lblRehabilitationFacilities.setText("Используемые тех средства реабилитации");

        lblPlaceOfWork.setText("Место работы");

        lblWelfareLavel.setText("Уровень благосостояния");

        lblEducation.setText("Образование");

        lblMaritalStatus.setText("Семейное положение");

        comboBoxRehabilitationFacilities.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "другое", "коляска", "костыли", "трость" }));

        comboBoxWelfareLavel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "высокий", "средний", "ниже среднего", "низкий" }));

        comboBoxEducation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "высшее", "среднее", "школьное", "нет" }));

        comboBoxMaritalStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "семейный/ая", "одинокий/ая", "на иждевении", "другое" }));

        comboBoxPrimaryViolations.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelSocialCharacteristicLayout = new javax.swing.GroupLayout(panelSocialCharacteristic);
        panelSocialCharacteristic.setLayout(panelSocialCharacteristicLayout);
        panelSocialCharacteristicLayout.setHorizontalGroup(
            panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSocialCharacteristicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDisabilityGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRehabilitationFacilities, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCauseOfDisability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDisabilityDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrimaryViolations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPlaceOfWork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblWelfareLavel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEducation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMaritalStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboBoxDisabilityGroup, 0, 193, Short.MAX_VALUE)
                    .addComponent(textFieldCauseOfDisability)
                    .addComponent(textFieldDisabilityDate)
                    .addComponent(comboBoxRehabilitationFacilities, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldPlaceOfWork)
                    .addComponent(comboBoxWelfareLavel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxEducation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxMaritalStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxPrimaryViolations, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(439, Short.MAX_VALUE))
        );
        panelSocialCharacteristicLayout.setVerticalGroup(
            panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSocialCharacteristicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisabilityGroup)
                    .addComponent(comboBoxDisabilityGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCauseOfDisability)
                    .addComponent(textFieldCauseOfDisability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisabilityDate)
                    .addComponent(textFieldDisabilityDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimaryViolations)
                    .addComponent(comboBoxPrimaryViolations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxRehabilitationFacilities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRehabilitationFacilities))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaceOfWork)
                    .addComponent(textFieldPlaceOfWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxWelfareLavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWelfareLavel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEducation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxMaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaritalStatus))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        tabbedPaneRegistrator.addTab("Социальная характеристика", panelSocialCharacteristic);

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addContainerGap())
            .addComponent(tabbedPaneRegistrator, javax.swing.GroupLayout.Alignment.LEADING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPaneRegistrator)
                .addGap(18, 18, 18)
                .addComponent(btnOk)
                .addContainerGap())
        );

        tabbedPaneRegistrator.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Кнопка записи заполненных данных в БД
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        Component frame = null;
        if(textFieldFamily.getText().equals("") || textFieldName.getText().equals("") || textFieldDataBirth.getText().equals("") || 
                textFieldSnils.getText().equals("") || textFieldPasportSeries.getText().equals("") || textFieldPasportNumber.getText().equals("") ||
                textFieldIssuedBy.getText().equals("") || textFieldDateOfIssue.getText().equals("")){
            JOptionPane.showMessageDialog(frame,"Необходимо заполнить все поля","ВНИМАНИЕ",JOptionPane.WARNING_MESSAGE);
        } else{    
            if(db.sendInsert("INSERT INTO medunica.clients (family, name, patronomic, date_birth, snils, gender, pasport_series, pasport_number, issued_by, date_of_issue, residence_address,"
                + " permanent_registration, disability_group, cause_of_disability, disability_date, primary_violations, rehabilitation_facilities, place_of_work, welfare_level, "
                + " education, marital_status)"
                + " VALUES('"+textFieldFamily.getText()+"', '"+textFieldName.getText()+"', '"+textFieldPatron.getText()+"', '"+textFieldDataBirth.getText()+"', '"+textFieldSnils.getText()+"', 'пол',"
                + " '"+textFieldPasportSeries.getText()+"', '"+textFieldPasportNumber.getText()+"', '"+textFieldIssuedBy.getText()+"', '"+textFieldDateOfIssue.getText()+"',"
                + " '"+textFieldResidenceAddress.getText()+"', '"+textFieldPermanentRegistration.getText()+"', 'группа инвалидности', '"+textFieldCauseOfDisability.getText()+"',"
                + " '"+textFieldDisabilityDate.getText()+"', 'преимущественные нарушения', 'Используемые тех средства реабилитации', '"+textFieldPlaceOfWork.getText()+"', "
                + "'Уровень благосостояния', 'Образование', 'Семейное положение')")){
                JOptionPane.showMessageDialog(frame,"Данные успешно добавлены","МЕДУНИЦА",JOptionPane.INFORMATION_MESSAGE);
                clearTexField();
            } else {
                JOptionPane.showMessageDialog(frame,"Ошибка отправки запроса","ОШИБКА",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnOkActionPerformed

    private void radioButtonGenderMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonGenderMActionPerformed
        // TODO add your handling code here:
        radioButtonGenderG.setSelected(false);
    }//GEN-LAST:event_radioButtonGenderMActionPerformed

    private void radioButtonGenderGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonGenderGActionPerformed
        // TODO add your handling code here:
        radioButtonGenderM.setSelected(false);
    }//GEN-LAST:event_radioButtonGenderGActionPerformed

    // Очистка полей ввода данных
    private void clearTexField(){
        textFieldFamily.setText(""); textFieldName.setText(""); textFieldPatron.setText(""); textFieldDataBirth.setText(""); textFieldSnils.setText("");
        textFieldPasportSeries.setText(""); textFieldPasportNumber.setText(""); textFieldIssuedBy.setText(""); textFieldDateOfIssue.setText("");
        textFieldResidenceAddress.setText(""); textFieldPermanentRegistration.setText(""); textFieldIpr.setText(""); textFieldIprData.setText("");
        textFieldTelephone.setText(""); textFieldEmail.setText(""); textFieldCauseOfDisability.setText(""); textFieldDisabilityDate.setText(""); textFieldPlaceOfWork.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> comboBoxDisabilityGroup;
    private javax.swing.JComboBox<String> comboBoxEducation;
    private javax.swing.JComboBox<String> comboBoxMaritalStatus;
    private javax.swing.JComboBox<String> comboBoxPrimaryViolations;
    private javax.swing.JComboBox<String> comboBoxRehabilitationFacilities;
    private javax.swing.JComboBox<String> comboBoxWelfareLavel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCauseOfDisability;
    private javax.swing.JLabel lblDataBirth;
    private javax.swing.JLabel lblDateOfIssue;
    private javax.swing.JLabel lblDisabilityDate;
    private javax.swing.JLabel lblDisabilityGroup;
    private javax.swing.JLabel lblEducation;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFamily;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblIpr;
    private javax.swing.JLabel lblIprData;
    private javax.swing.JLabel lblIssuedBy;
    private javax.swing.JLabel lblMaritalStatus;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPasportNumber;
    private javax.swing.JLabel lblPasportSeries;
    private javax.swing.JLabel lblPatron;
    private javax.swing.JLabel lblPermanentRegistration;
    private javax.swing.JLabel lblPlaceOfWork;
    private javax.swing.JLabel lblPrimaryViolations;
    private javax.swing.JLabel lblRehabilitationFacilities;
    private javax.swing.JLabel lblResidenceAddress;
    private javax.swing.JLabel lblSnils;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JLabel lblWelfareLavel;
    private javax.swing.JPanel panelGeneralInformation;
    private javax.swing.JPanel panelSocialCharacteristic;
    private javax.swing.JRadioButton radioButtonGenderG;
    private javax.swing.JRadioButton radioButtonGenderM;
    private javax.swing.JTabbedPane tabbedPaneRegistrator;
    private javax.swing.JTextField textFieldCauseOfDisability;
    private javax.swing.JTextField textFieldDataBirth;
    private javax.swing.JTextField textFieldDateOfIssue;
    private javax.swing.JTextField textFieldDisabilityDate;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldFamily;
    private javax.swing.JTextField textFieldIpr;
    private javax.swing.JTextField textFieldIprData;
    private javax.swing.JTextField textFieldIssuedBy;
    private javax.swing.JTextField textFieldName;
    private javax.swing.JTextField textFieldPasportNumber;
    private javax.swing.JTextField textFieldPasportSeries;
    private javax.swing.JTextField textFieldPatron;
    private javax.swing.JTextField textFieldPermanentRegistration;
    private javax.swing.JTextField textFieldPlaceOfWork;
    private javax.swing.JTextField textFieldResidenceAddress;
    private javax.swing.JTextField textFieldSnils;
    private javax.swing.JTextField textFieldTelephone;
    // End of variables declaration//GEN-END:variables
}
