/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medunica;

import java.awt.Component;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


/**
 *
 * @author LEX
 */
public class Registrator extends javax.swing.JFrame {

    DataBase db = null;
    /**
     * Creates new form Registrator
     */
    public Registrator(){
        initComponents(); 
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("medunica.jpg")));
        db = new DataBase("jdbc:mysql://localhost/medunica?character_set_server=utf8mb4&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "root", "toor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPaneRegistrator = new javax.swing.JTabbedPane();
        panelGeneralInformation = new javax.swing.JPanel();
        lblPasportSeries = new javax.swing.JLabel();
        lblPasportNumber = new javax.swing.JLabel();
        textFieldPermanentRegistration = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblDateOfIssue = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblTelephone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        radioButtonGenderM = new javax.swing.JRadioButton();
        radioButtonGenderG = new javax.swing.JRadioButton();
        lblResidenceAddress = new javax.swing.JLabel();
        lblFamily = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPermanentRegistration = new javax.swing.JLabel();
        lblPatron = new javax.swing.JLabel();
        textFieldResidenceAddress = new javax.swing.JTextField();
        textFieldFamily = new javax.swing.JTextField();
        lblIpr = new javax.swing.JLabel();
        textFieldName = new javax.swing.JTextField();
        textFieldIpr = new javax.swing.JTextField();
        textFieldPatron = new javax.swing.JTextField();
        lblIprData = new javax.swing.JLabel();
        lblDataBirth = new javax.swing.JLabel();
        lblSnils = new javax.swing.JLabel();
        formattedTextFieldSnils = new javax.swing.JFormattedTextField();
        formattedTextFieldPasportSeries = new javax.swing.JFormattedTextField();
        formattedTextFieldPasportNumber = new javax.swing.JFormattedTextField();
        lblIssuedBy = new javax.swing.JLabel();
        formattedTextFieldDateOfIssue = new javax.swing.JFormattedTextField();
        textFieldIssuedBy = new javax.swing.JTextField();
        formattedTextFieldTelephone = new javax.swing.JFormattedTextField();
        formattedTextFieldIprData = new javax.swing.JFormattedTextField();
        jSeparator3 = new javax.swing.JSeparator();
        formattedTextFieldEmail = new javax.swing.JFormattedTextField();
        formattedTextFieldDateBirth = new javax.swing.JFormattedTextField();
        panelSocialCharacteristic = new javax.swing.JPanel();
        lblDisabilityGroup = new javax.swing.JLabel();
        lblCauseOfDisability = new javax.swing.JLabel();
        lblDisabilityDate = new javax.swing.JLabel();
        lblPrimaryViolations = new javax.swing.JLabel();
        comboBoxDisabilityGroup = new javax.swing.JComboBox<>();
        lblRehabilitationFacilities = new javax.swing.JLabel();
        lblPlaceOfWork = new javax.swing.JLabel();
        lblWelfareLavel = new javax.swing.JLabel();
        lblEducation = new javax.swing.JLabel();
        lblMaritalStatus = new javax.swing.JLabel();
        textFieldCauseOfDisability = new javax.swing.JTextField();
        comboBoxRehabilitationFacilities = new javax.swing.JComboBox<>();
        textFieldPlaceOfWork = new javax.swing.JTextField();
        comboBoxWelfareLavel = new javax.swing.JComboBox<>();
        comboBoxEducation = new javax.swing.JComboBox<>();
        comboBoxMaritalStatus = new javax.swing.JComboBox<>();
        comboBoxPrimaryViolations = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        formattedTextFieldDisabilityDate = new javax.swing.JFormattedTextField();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("МЕДУНИЦА РЕГИСТРАТОР");

        lblPasportSeries.setText("Серия паспорта");

        lblPasportNumber.setText("Номер паспорта");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");

        lblDateOfIssue.setText("Дата выдачи");

        lblTelephone.setText("Телефон");

        lblEmail.setText("Эл.почта");

        lblGender.setText("Пол");

        radioButtonGenderM.setText("М");
        radioButtonGenderM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonGenderMActionPerformed(evt);
            }
        });

        radioButtonGenderG.setText("Ж");
        radioButtonGenderG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonGenderGActionPerformed(evt);
            }
        });

        lblResidenceAddress.setText("Адрес места жительства");

        lblFamily.setText("Фамилия");

        lblName.setText("Имя");

        lblPermanentRegistration.setText("Место постоянной регистрации");

        lblPatron.setText("Отчество");

        lblIpr.setText("ИПР/ИПРА");

        lblIprData.setText("Дата разработки ИПР/ИПРА");

        lblDataBirth.setText("ДатаРождения");

        lblSnils.setText("СНИЛС");

        try {
            formattedTextFieldSnils.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            formattedTextFieldPasportSeries.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            formattedTextFieldPasportNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblIssuedBy.setText("Кем выдан");

        try {
            formattedTextFieldDateOfIssue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            formattedTextFieldTelephone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+7(###)###-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            formattedTextFieldIprData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        try {
            formattedTextFieldDateBirth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout panelGeneralInformationLayout = new javax.swing.GroupLayout(panelGeneralInformation);
        panelGeneralInformation.setLayout(panelGeneralInformationLayout);
        panelGeneralInformationLayout.setHorizontalGroup(
            panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPatron, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDataBirth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFamily, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSnils, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                                .addComponent(radioButtonGenderM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioButtonGenderG))
                            .addComponent(textFieldName)
                            .addComponent(textFieldFamily)
                            .addComponent(textFieldPatron)
                            .addComponent(formattedTextFieldDateBirth)
                            .addComponent(formattedTextFieldSnils, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(formattedTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                                .addComponent(lblPasportSeries)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(formattedTextFieldPasportSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPasportNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDateOfIssue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(formattedTextFieldPasportNumber)
                                    .addComponent(formattedTextFieldDateOfIssue)
                                    .addComponent(formattedTextFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblIssuedBy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPermanentRegistration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblResidenceAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblIpr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblIprData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textFieldPermanentRegistration)
                                .addComponent(textFieldResidenceAddress)
                                .addComponent(textFieldIssuedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(formattedTextFieldIprData, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFieldIpr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGeneralInformationLayout.setVerticalGroup(
            panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                            .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFamily)
                                .addComponent(textFieldFamily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblName)
                                .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPatron)
                                .addComponent(textFieldPatron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDataBirth)
                                .addComponent(formattedTextFieldDateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSnils)
                                .addComponent(formattedTextFieldSnils, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioButtonGenderG)
                                    .addComponent(radioButtonGenderM))
                                .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPasportSeries)
                                .addComponent(formattedTextFieldPasportSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPasportNumber)
                                .addComponent(formattedTextFieldPasportNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDateOfIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(formattedTextFieldDateOfIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(formattedTextFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEmail)
                                .addComponent(formattedTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addComponent(jSeparator3))
                    .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblResidenceAddress)
                                    .addComponent(textFieldResidenceAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPermanentRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldPermanentRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblIssuedBy)
                                    .addComponent(textFieldIssuedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62)))
                        .addGap(28, 28, 28)
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIpr)
                            .addComponent(textFieldIpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIprData, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formattedTextFieldIprData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tabbedPaneRegistrator.addTab("Общие данные", panelGeneralInformation);

        lblDisabilityGroup.setText("Группа инвалидности");

        lblCauseOfDisability.setText("Причина инвалидности");

        lblDisabilityDate.setText("Дата установки инвалидности");

        lblPrimaryViolations.setText("Преимущественные нарушения");

        comboBoxDisabilityGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "нет", "1", "2", "3" }));

        lblRehabilitationFacilities.setText("Используемые тех средства реабилитации");

        lblPlaceOfWork.setText("Место работы");

        lblWelfareLavel.setText("Уровень благосостояния");

        lblEducation.setText("Образование");

        lblMaritalStatus.setText("Семейное положение");

        comboBoxRehabilitationFacilities.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "другое", "коляска", "костыли", "трость" }));

        comboBoxWelfareLavel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "высокий", "средний", "ниже среднего", "низкий" }));

        comboBoxEducation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "высшее", "среднее", "школьное", "нет" }));

        comboBoxMaritalStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "семейный/ая", "одинокий/ая", "на иждевении", "другое" }));

        comboBoxPrimaryViolations.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        try {
            formattedTextFieldDisabilityDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout panelSocialCharacteristicLayout = new javax.swing.GroupLayout(panelSocialCharacteristic);
        panelSocialCharacteristic.setLayout(panelSocialCharacteristicLayout);
        panelSocialCharacteristicLayout.setHorizontalGroup(
            panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSocialCharacteristicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDisabilityGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRehabilitationFacilities, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCauseOfDisability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDisabilityDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrimaryViolations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldCauseOfDisability)
                    .addComponent(comboBoxDisabilityGroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxPrimaryViolations, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formattedTextFieldDisabilityDate)
                    .addComponent(comboBoxRehabilitationFacilities, 0, 116, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblWelfareLavel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEducation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMaritalStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPlaceOfWork, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comboBoxWelfareLavel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxEducation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxMaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textFieldPlaceOfWork, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        panelSocialCharacteristicLayout.setVerticalGroup(
            panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSocialCharacteristicLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelSocialCharacteristicLayout.createSequentialGroup()
                        .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDisabilityGroup)
                            .addComponent(comboBoxDisabilityGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCauseOfDisability)
                            .addComponent(textFieldCauseOfDisability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDisabilityDate)
                            .addComponent(formattedTextFieldDisabilityDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrimaryViolations)
                            .addComponent(comboBoxPrimaryViolations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxRehabilitationFacilities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRehabilitationFacilities)))
                    .addGroup(panelSocialCharacteristicLayout.createSequentialGroup()
                        .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxWelfareLavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWelfareLavel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSocialCharacteristicLayout.createSequentialGroup()
                                .addComponent(comboBoxEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboBoxMaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMaritalStatus)))
                            .addComponent(lblEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPlaceOfWork)
                            .addComponent(textFieldPlaceOfWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator4))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        tabbedPaneRegistrator.addTab("Социальная характеристика", panelSocialCharacteristic);

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(tabbedPaneRegistrator, javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPaneRegistrator, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addContainerGap())
        );

        tabbedPaneRegistrator.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Кнопка записи заполненных данных в БД
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        Component frame = null;
        String gender = "пол";
        if(radioButtonGenderM.isSelected()){
            gender = "мужской";
        }
        if(radioButtonGenderG.isSelected()){
            gender = "женский";
        }
        if(formattedTextFieldSnils.isEditValid()){
            if(textFieldFamily.getText().equals("") || textFieldName.getText().equals("") || formattedTextFieldDateBirth.getText().equals("") || 
                    formattedTextFieldPasportSeries.getText().equals("") || formattedTextFieldPasportNumber.getText().equals("") ||
                    textFieldIssuedBy.getText().equals("") || formattedTextFieldDateOfIssue.getText().equals("")){
                JOptionPane.showMessageDialog(frame,"Необходимо заполнить все поля","ВНИМАНИЕ",JOptionPane.WARNING_MESSAGE);
            } else{    
                if(db.sendInsert("INSERT INTO medunica.clients (family, name, patronomic, date_birth, snils, gender, ipr, ipr_date, telephone, email, pasport_series, pasport_number, issued_by, date_of_issue, residence_address,"
                    + " permanent_registration, disability_group, cause_of_disability, disability_date, primary_violations, rehabilitation_facilities, place_of_work, welfare_level, "
                    + " education, marital_status)"
                    + " VALUES('"+textFieldFamily.getText()+"', '"+textFieldName.getText()+"', '"+textFieldPatron.getText()+"', '"+formattedTextFieldDateBirth.getText()+"', '"+formattedTextFieldSnils.getText()+"', '"+gender+"',"
                    + " '"+textFieldIpr.getText()+"', '"+formattedTextFieldIprData.getText()+"' , '"+formattedTextFieldTelephone.getText()+"', '"+formattedTextFieldEmail.getText()+"',"
                    + " '"+formattedTextFieldPasportSeries.getText()+"', '"+formattedTextFieldPasportNumber.getText()+"', '"+textFieldIssuedBy.getText()+"', '"+formattedTextFieldDateOfIssue.getText()+"',"
                    + " '"+textFieldResidenceAddress.getText()+"', '"+textFieldPermanentRegistration.getText()+"', '"+comboBoxDisabilityGroup.getSelectedItem()+"', '"+textFieldCauseOfDisability.getText()+"',"
                    + " '"+formattedTextFieldDisabilityDate.getText()+"', '"+comboBoxPrimaryViolations.getSelectedItem()+"', '"+comboBoxRehabilitationFacilities.getSelectedItem()+"', '"+textFieldPlaceOfWork.getText()+"', "
                    + " '"+comboBoxWelfareLavel.getSelectedItem()+"', '"+comboBoxEducation.getSelectedItem()+"', '"+comboBoxMaritalStatus.getSelectedItem()+"')")){
                    JOptionPane.showMessageDialog(frame,"Данные успешно добавлены","МЕДУНИЦА",JOptionPane.INFORMATION_MESSAGE);
                    clearTexField();
                } else {
                    JOptionPane.showMessageDialog(frame,"Ошибка отправки запроса","ОШИБКА",JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(frame,"Необходимо ввести СНИЛС","ОШИБКА",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void radioButtonGenderMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonGenderMActionPerformed
        // TODO add your handling code here:
        radioButtonGenderG.setSelected(false);
    }//GEN-LAST:event_radioButtonGenderMActionPerformed

    private void radioButtonGenderGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonGenderGActionPerformed
        // TODO add your handling code here:
        radioButtonGenderM.setSelected(false);
    }//GEN-LAST:event_radioButtonGenderGActionPerformed

    // Очистка полей ввода данных
    private void clearTexField(){
        textFieldFamily.setText(""); textFieldName.setText(""); textFieldPatron.setText(""); formattedTextFieldDateBirth.setText(""); formattedTextFieldSnils.setText("");
        formattedTextFieldPasportSeries.setText(""); formattedTextFieldPasportNumber.setText(""); textFieldIssuedBy.setText(""); formattedTextFieldDateOfIssue.setText("");
        textFieldResidenceAddress.setText(""); textFieldPermanentRegistration.setText(""); textFieldIpr.setText(""); formattedTextFieldIprData.setText("");
        formattedTextFieldTelephone.setText(""); formattedTextFieldEmail.setText(""); textFieldCauseOfDisability.setText(""); formattedTextFieldDisabilityDate.setText(""); textFieldPlaceOfWork.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> comboBoxDisabilityGroup;
    private javax.swing.JComboBox<String> comboBoxEducation;
    private javax.swing.JComboBox<String> comboBoxMaritalStatus;
    private javax.swing.JComboBox<String> comboBoxPrimaryViolations;
    private javax.swing.JComboBox<String> comboBoxRehabilitationFacilities;
    private javax.swing.JComboBox<String> comboBoxWelfareLavel;
    private javax.swing.JFormattedTextField formattedTextFieldDateBirth;
    private javax.swing.JFormattedTextField formattedTextFieldDateOfIssue;
    private javax.swing.JFormattedTextField formattedTextFieldDisabilityDate;
    private javax.swing.JFormattedTextField formattedTextFieldEmail;
    private javax.swing.JFormattedTextField formattedTextFieldIprData;
    private javax.swing.JFormattedTextField formattedTextFieldPasportNumber;
    private javax.swing.JFormattedTextField formattedTextFieldPasportSeries;
    private javax.swing.JFormattedTextField formattedTextFieldSnils;
    private javax.swing.JFormattedTextField formattedTextFieldTelephone;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblCauseOfDisability;
    private javax.swing.JLabel lblDataBirth;
    private javax.swing.JLabel lblDateOfIssue;
    private javax.swing.JLabel lblDisabilityDate;
    private javax.swing.JLabel lblDisabilityGroup;
    private javax.swing.JLabel lblEducation;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFamily;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblIpr;
    private javax.swing.JLabel lblIprData;
    private javax.swing.JLabel lblIssuedBy;
    private javax.swing.JLabel lblMaritalStatus;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPasportNumber;
    private javax.swing.JLabel lblPasportSeries;
    private javax.swing.JLabel lblPatron;
    private javax.swing.JLabel lblPermanentRegistration;
    private javax.swing.JLabel lblPlaceOfWork;
    private javax.swing.JLabel lblPrimaryViolations;
    private javax.swing.JLabel lblRehabilitationFacilities;
    private javax.swing.JLabel lblResidenceAddress;
    private javax.swing.JLabel lblSnils;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JLabel lblWelfareLavel;
    private javax.swing.JPanel panelGeneralInformation;
    private javax.swing.JPanel panelSocialCharacteristic;
    private javax.swing.JRadioButton radioButtonGenderG;
    private javax.swing.JRadioButton radioButtonGenderM;
    private javax.swing.JTabbedPane tabbedPaneRegistrator;
    private javax.swing.JTextField textFieldCauseOfDisability;
    private javax.swing.JTextField textFieldFamily;
    private javax.swing.JTextField textFieldIpr;
    private javax.swing.JTextField textFieldIssuedBy;
    private javax.swing.JTextField textFieldName;
    private javax.swing.JTextField textFieldPatron;
    private javax.swing.JTextField textFieldPermanentRegistration;
    private javax.swing.JTextField textFieldPlaceOfWork;
    private javax.swing.JTextField textFieldResidenceAddress;
    // End of variables declaration//GEN-END:variables
}
