/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medunica;

import java.awt.Component;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author LEX
 */
public class Registrator extends javax.swing.JFrame {

    DataBase db = null;
    /**
     * Creates new form Registrator
     */
    public Registrator(){
        initComponents(); 
        
        // загрузка иконки
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("medunica.jpg")));
        
        // подключение к базе
        db = new DataBase("jdbc:mysql://localhost/medunica?character_set_server=utf8mb4&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "root", "toor");
        
        // установка текущей даты в графу "Дата поступления"
        DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        Calendar cal = Calendar.getInstance();
        formattedTextFieldReceiptDate.setText(dateFormat.format(cal.getTime()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialogReceiptDate = new datechooser.beans.DateChooserDialog();
        tabbedPaneRegistrator = new javax.swing.JTabbedPane();
        panelGeneralInformation = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lblFamily = new javax.swing.JLabel();
        textFieldFamily = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        textFieldName = new javax.swing.JTextField();
        lblPatron = new javax.swing.JLabel();
        textFieldPatron = new javax.swing.JTextField();
        lblDataBirth = new javax.swing.JLabel();
        formattedTextFieldDateBirth = new javax.swing.JFormattedTextField();
        lblSnils = new javax.swing.JLabel();
        formattedTextFieldSnils = new javax.swing.JFormattedTextField();
        lblGender = new javax.swing.JLabel();
        radioButtonGenderM = new javax.swing.JRadioButton();
        radioButtonGenderG = new javax.swing.JRadioButton();
        lblReceiptDate = new javax.swing.JLabel();
        formattedTextFieldReceiptDate = new javax.swing.JFormattedTextField();
        btnReceiptDateCalendar = new javax.swing.JButton();
        btnDataBirthCalendar = new javax.swing.JButton();
        btnDataBirthCalendar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblPasportSeries = new javax.swing.JLabel();
        formattedTextFieldPasportSeries = new javax.swing.JFormattedTextField();
        formattedTextFieldPasportNumber = new javax.swing.JFormattedTextField();
        lblPasportNumber = new javax.swing.JLabel();
        lblDateOfIssue = new javax.swing.JLabel();
        formattedTextFieldDateOfIssue = new javax.swing.JFormattedTextField();
        lblTelephone = new javax.swing.JLabel();
        formattedTextFieldTelephone = new javax.swing.JFormattedTextField();
        lblEmail = new javax.swing.JLabel();
        formattedTextFieldEmail = new javax.swing.JFormattedTextField();
        btnDateOfIssueCalendar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblIssuedBy = new javax.swing.JLabel();
        textFieldIssuedBy = new javax.swing.JTextField();
        lblResidenceAddress = new javax.swing.JLabel();
        textFieldResidenceAddress = new javax.swing.JTextField();
        lblPermanentRegistration = new javax.swing.JLabel();
        textFieldPermanentRegistration = new javax.swing.JTextField();
        lblIpr = new javax.swing.JLabel();
        textFieldIpr = new javax.swing.JTextField();
        lblIprData = new javax.swing.JLabel();
        formattedTextFieldIprData = new javax.swing.JFormattedTextField();
        lblServiseForm = new javax.swing.JLabel();
        comboBoxServiceForm = new javax.swing.JComboBox<>();
        btnIprDateCalendar = new javax.swing.JButton();
        panelSocialCharacteristic = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        lblDisabilityGroup = new javax.swing.JLabel();
        comboBoxDisabilityGroup = new javax.swing.JComboBox<>();
        lblCauseOfDisability = new javax.swing.JLabel();
        textFieldCauseOfDisability = new javax.swing.JTextField();
        lblDisabilityDate = new javax.swing.JLabel();
        formattedTextFieldDisabilityDate = new javax.swing.JFormattedTextField();
        btnDisabilityDateCalendar = new javax.swing.JButton();
        lblPrimaryViolations = new javax.swing.JLabel();
        comboBoxPrimaryViolations = new javax.swing.JComboBox<>();
        lblRehabilitationFacilities = new javax.swing.JLabel();
        comboBoxRehabilitationFacilities = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        lblWelfareLavel = new javax.swing.JLabel();
        lblEducation = new javax.swing.JLabel();
        lblMaritalStatus = new javax.swing.JLabel();
        lblPlaceOfWork = new javax.swing.JLabel();
        comboBoxWelfareLavel = new javax.swing.JComboBox<>();
        comboBoxEducation = new javax.swing.JComboBox<>();
        comboBoxMaritalStatus = new javax.swing.JComboBox<>();
        textFieldPlaceOfWork = new javax.swing.JTextField();
        lblNamberOfFamily = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        lblNumberMinorChildren = new javax.swing.JLabel();
        spinnerNumberMinorChildren = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        lblRecipientIncome12Months = new javax.swing.JLabel();
        formattedTextFieldRecipientIncome12Months = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        lblSpousesIncome12Months = new javax.swing.JLabel();
        formattedTextFieldIncomeMotherFather = new javax.swing.JFormattedTextField();
        comboBoxSpousesIncome12Months = new javax.swing.JComboBox<>();
        formattedTextFieldSpousesIncome12Months1 = new javax.swing.JFormattedTextField();
        lblIncomeMotherFather = new javax.swing.JLabel();
        formattedTextFieldRecipientsPerCapitaIncome = new javax.swing.JFormattedTextField();
        comboBoxIncomeMotherFather = new javax.swing.JComboBox<>();
        formattedTextFieldAverageRevenue = new javax.swing.JFormattedTextField();
        lblAmountIncomeAllFamily = new javax.swing.JLabel();
        formattedTextFieldSpousesIncome12Months = new javax.swing.JFormattedTextField();
        lblAverageRevenue = new javax.swing.JLabel();
        formattedTextFieldIncomeMotherFather1 = new javax.swing.JFormattedTextField();
        lblRecipientsPerCapitaIncome = new javax.swing.JLabel();
        formattedTextFieldAmountIncomeAllFamily = new javax.swing.JFormattedTextField();
        lbl75pRecipientIncome = new javax.swing.JLabel();
        formattedTextField75pRecipientIncome = new javax.swing.JFormattedTextField();
        lblCapPerCapitaIncome = new javax.swing.JLabel();
        formattedTextFieldCapPerCapitaIncome = new javax.swing.JFormattedTextField();
        lblDifferencePerCapitaIncome = new javax.swing.JLabel();
        formattedTextFieldDifferencePerCapitaIncome = new javax.swing.JFormattedTextField();
        formattedTextFieldActualNumberDays = new javax.swing.JFormattedTextField();
        formattedTextFieldNumberDaysMonth = new javax.swing.JFormattedTextField();
        lblNumberDaysMonth = new javax.swing.JLabel();
        lblActualNumberDays = new javax.swing.JLabel();
        formattedTextFieldActualContractAmount = new javax.swing.JFormattedTextField();
        formattedTextFieldContract24Days = new javax.swing.JFormattedTextField();
        lblContract24Days = new javax.swing.JLabel();
        lblActualContractAmount = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnDischarge = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("МЕДУНИЦА РЕГИСТРАТОР");

        lblFamily.setText("Фамилия");

        lblName.setText("Имя");

        lblPatron.setText("Отчество");

        lblDataBirth.setText("ДатаРождения");

        try {
            formattedTextFieldDateBirth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblSnils.setText("СНИЛС");

        try {
            formattedTextFieldSnils.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblGender.setText("Пол");

        radioButtonGenderM.setText("М");
        radioButtonGenderM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonGenderMActionPerformed(evt);
            }
        });

        radioButtonGenderG.setText("Ж");
        radioButtonGenderG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonGenderGActionPerformed(evt);
            }
        });

        lblReceiptDate.setText("Дата поступления");

        try {
            formattedTextFieldReceiptDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnReceiptDateCalendar.setText("...");
        btnReceiptDateCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiptDateCalendarActionPerformed(evt);
            }
        });

        btnDataBirthCalendar.setText("...");
        btnDataBirthCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataBirthCalendarActionPerformed(evt);
            }
        });

        btnDataBirthCalendar1.setText("...");
        btnDataBirthCalendar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataBirthCalendar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblReceiptDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPatron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDataBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFamily, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSnils, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radioButtonGenderM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioButtonGenderG)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textFieldName)
                    .addComponent(textFieldFamily)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(formattedTextFieldDateBirth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDataBirthCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(formattedTextFieldSnils, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDataBirthCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(formattedTextFieldReceiptDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReceiptDateCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textFieldPatron))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFamily)
                    .addComponent(textFieldFamily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatron)
                    .addComponent(textFieldPatron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDataBirthCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDataBirth)
                        .addComponent(formattedTextFieldDateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSnils)
                    .addComponent(formattedTextFieldSnils, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDataBirthCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioButtonGenderG)
                        .addComponent(radioButtonGenderM))
                    .addComponent(lblGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReceiptDate)
                    .addComponent(formattedTextFieldReceiptDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReceiptDateCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        lblPasportSeries.setText("Серия паспорта");

        try {
            formattedTextFieldPasportSeries.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            formattedTextFieldPasportNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblPasportNumber.setText("Номер паспорта");

        lblDateOfIssue.setText("Дата выдачи");

        try {
            formattedTextFieldDateOfIssue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblTelephone.setText("Телефон");

        try {
            formattedTextFieldTelephone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+7(###)###-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblEmail.setText("Эл.почта");

        btnDateOfIssueCalendar.setText("...");
        btnDateOfIssueCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateOfIssueCalendarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(formattedTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblPasportSeries)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(formattedTextFieldPasportSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPasportNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDateOfIssue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(formattedTextFieldPasportNumber)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(formattedTextFieldDateOfIssue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDateOfIssueCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(formattedTextFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasportSeries)
                    .addComponent(formattedTextFieldPasportSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasportNumber)
                    .addComponent(formattedTextFieldPasportNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formattedTextFieldDateOfIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDateOfIssueCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formattedTextFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(formattedTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        lblIssuedBy.setText("Кем выдан");

        lblResidenceAddress.setText("Адрес места жительства");

        lblPermanentRegistration.setText("Место постоянной регистрации");

        lblIpr.setText("ИПР/ИПРА");

        lblIprData.setText("Дата разработки ИПР/ИПРА");

        try {
            formattedTextFieldIprData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblServiseForm.setText("Форма получения услуг");

        comboBoxServiceForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "стационар", "полустационар" }));

        btnIprDateCalendar.setText("...");
        btnIprDateCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIprDateCalendarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblServiseForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIssuedBy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPermanentRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblResidenceAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIpr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIprData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textFieldPermanentRegistration)
                        .addComponent(textFieldResidenceAddress)
                        .addComponent(textFieldIssuedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboBoxServiceForm, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(formattedTextFieldIprData)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnIprDateCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(textFieldIpr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblResidenceAddress)
                            .addComponent(textFieldResidenceAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPermanentRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldPermanentRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIssuedBy)
                            .addComponent(textFieldIssuedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIpr)
                    .addComponent(textFieldIpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIprData, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formattedTextFieldIprData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIprDateCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServiseForm)
                    .addComponent(comboBoxServiceForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGeneralInformationLayout = new javax.swing.GroupLayout(panelGeneralInformation);
        panelGeneralInformation.setLayout(panelGeneralInformationLayout);
        panelGeneralInformationLayout.setHorizontalGroup(
            panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        panelGeneralInformationLayout.setVerticalGroup(
            panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        tabbedPaneRegistrator.addTab("Общие данные", panelGeneralInformation);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblDisabilityGroup.setText("Группа инвалидности");

        comboBoxDisabilityGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "нет", "1", "2", "3" }));

        lblCauseOfDisability.setText("Причина инвалидности");

        lblDisabilityDate.setText("Дата установки инвалидности");

        try {
            formattedTextFieldDisabilityDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnDisabilityDateCalendar.setText("...");
        btnDisabilityDateCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisabilityDateCalendarActionPerformed(evt);
            }
        });

        lblPrimaryViolations.setText("Преимущественные нарушения");

        comboBoxPrimaryViolations.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "прочее", "в/конечностей", "н/конечностей", "слуха", "зренеия", "психики" }));

        lblRehabilitationFacilities.setText("Используемые тех средства реабилитации");

        comboBoxRehabilitationFacilities.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "другое", "коляска", "костыли", "трость" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDisabilityGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRehabilitationFacilities, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCauseOfDisability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDisabilityDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrimaryViolations, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldCauseOfDisability)
                    .addComponent(comboBoxDisabilityGroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxPrimaryViolations, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(formattedTextFieldDisabilityDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDisabilityDateCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboBoxRehabilitationFacilities, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisabilityGroup)
                    .addComponent(comboBoxDisabilityGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCauseOfDisability)
                    .addComponent(textFieldCauseOfDisability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisabilityDate)
                    .addComponent(formattedTextFieldDisabilityDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisabilityDateCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimaryViolations)
                    .addComponent(comboBoxPrimaryViolations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxRehabilitationFacilities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRehabilitationFacilities))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblWelfareLavel.setText("Уровень благосостояния");

        lblEducation.setText("Образование");

        lblMaritalStatus.setText("Семейное положение");

        lblPlaceOfWork.setText("Место работы");

        comboBoxWelfareLavel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "высокий", "средний", "ниже среднего", "низкий" }));

        comboBoxEducation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "высшее", "среднее", "школьное", "нет" }));

        comboBoxMaritalStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "семейный/ая", "одинокий/ая", "на иждевении", "другое" }));

        lblNamberOfFamily.setText("Количество членов семьи");

        lblNumberMinorChildren.setText("Количество несовершенно летних детей");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumberMinorChildren, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamberOfFamily, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPlaceOfWork, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWelfareLavel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboBoxWelfareLavel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxEducation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner1)
                    .addComponent(comboBoxMaritalStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldPlaceOfWork)
                    .addComponent(spinnerNumberMinorChildren))
                .addGap(17, 17, 17))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxWelfareLavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWelfareLavel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldPlaceOfWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlaceOfWork))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxMaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaritalStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamberOfFamily))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerNumberMinorChildren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumberMinorChildren))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelSocialCharacteristicLayout = new javax.swing.GroupLayout(panelSocialCharacteristic);
        panelSocialCharacteristic.setLayout(panelSocialCharacteristicLayout);
        panelSocialCharacteristicLayout.setHorizontalGroup(
            panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSocialCharacteristicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        panelSocialCharacteristicLayout.setVerticalGroup(
            panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSocialCharacteristicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(panelSocialCharacteristicLayout.createSequentialGroup()
                        .addGroup(panelSocialCharacteristicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 95, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabbedPaneRegistrator.addTab("Социальная характеристика", panelSocialCharacteristic);

        lblRecipientIncome12Months.setText("Доход получателя с. у. за 12 месяцев всего");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "зарплата", "ЕДВ", "пенсия" }));

        lblSpousesIncome12Months.setText("Доход супруга (а) за 12 месяцев всего");

        comboBoxSpousesIncome12Months.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "зарплата", "ЕДВ", "пенсия" }));

        lblIncomeMotherFather.setText("Доход мать (отец) за 12 месяцев всего");

        comboBoxIncomeMotherFather.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "зарплата", "ЕДВ", "пенсия" }));

        lblAmountIncomeAllFamily.setText("Cумма доходов всех членов семьи за 12 мес");

        lblAverageRevenue.setText("Cредняя сумма дохода за 12 месяцев ");

        lblRecipientsPerCapitaIncome.setText("среднедушевой доход получателя с.у.");

        lbl75pRecipientIncome.setText("75% среднедушевого дохода получателя");

        lblCapPerCapitaIncome.setText("предельная величина среднедушевого дохода");

        lblDifferencePerCapitaIncome.setText("Разница среднедушевого дохода");

        lblNumberDaysMonth.setText("количество дней в месяце подачи заявления");

        lblActualNumberDays.setText("фактическое количество дней");

        lblContract24Days.setText("сумма договора на 24 дня");

        lblActualContractAmount.setText("фактическая сумма договора");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblRecipientsPerCapitaIncome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRecipientIncome12Months, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSpousesIncome12Months, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIncomeMotherFather, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAmountIncomeAllFamily, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAverageRevenue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formattedTextFieldAverageRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formattedTextFieldRecipientsPerCapitaIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(formattedTextFieldRecipientIncome12Months, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(formattedTextFieldSpousesIncome12Months, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboBoxSpousesIncome12Months, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(formattedTextFieldIncomeMotherFather, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboBoxIncomeMotherFather, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(formattedTextFieldAmountIncomeAllFamily, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(formattedTextFieldSpousesIncome12Months1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(formattedTextFieldIncomeMotherFather1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lbl75pRecipientIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(formattedTextField75pRecipientIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDifferencePerCapitaIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCapPerCapitaIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formattedTextFieldCapPerCapitaIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formattedTextFieldDifferencePerCapitaIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblActualNumberDays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNumberDaysMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formattedTextFieldNumberDaysMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formattedTextFieldActualNumberDays, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblActualContractAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblContract24Days, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formattedTextFieldContract24Days, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formattedTextFieldActualContractAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRecipientIncome12Months, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formattedTextFieldRecipientIncome12Months, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSpousesIncome12Months)
                            .addComponent(formattedTextFieldSpousesIncome12Months, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxSpousesIncome12Months, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formattedTextFieldSpousesIncome12Months1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIncomeMotherFather)
                            .addComponent(formattedTextFieldIncomeMotherFather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxIncomeMotherFather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formattedTextFieldIncomeMotherFather1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAmountIncomeAllFamily)
                            .addComponent(formattedTextFieldAmountIncomeAllFamily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAverageRevenue)
                            .addComponent(formattedTextFieldAverageRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRecipientsPerCapitaIncome)
                            .addComponent(formattedTextFieldRecipientsPerCapitaIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl75pRecipientIncome)
                            .addComponent(formattedTextField75pRecipientIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCapPerCapitaIncome)
                            .addComponent(formattedTextFieldCapPerCapitaIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDifferencePerCapitaIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formattedTextFieldDifferencePerCapitaIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumberDaysMonth)
                            .addComponent(formattedTextFieldNumberDaysMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblActualNumberDays, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formattedTextFieldActualNumberDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContract24Days)
                            .addComponent(formattedTextFieldContract24Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblActualContractAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formattedTextFieldActualContractAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        tabbedPaneRegistrator.addTab("Оплата услуг", jPanel6);

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnDischarge.setText("Выписать");
        btnDischarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDischargeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDischarge)
                .addGap(129, 129, 129)
                .addComponent(btnOk)
                .addContainerGap())
            .addComponent(tabbedPaneRegistrator, javax.swing.GroupLayout.Alignment.LEADING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPaneRegistrator, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnDischarge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabbedPaneRegistrator.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Кнопка записи заполненных данных в БД
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        
        DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        Calendar cal = Calendar.getInstance();
        
        Component frame = null;
        String gender = "пол";
        if(radioButtonGenderM.isSelected()){
            gender = "мужской";
        }
        if(radioButtonGenderG.isSelected()){
            gender = "женский";
        }
        if(formattedTextFieldSnils.isEditValid()){
            if(textFieldFamily.getText().equals("") || textFieldName.getText().equals("") || formattedTextFieldDateBirth.getText().equals("") || 
                    formattedTextFieldPasportSeries.getText().equals("") || formattedTextFieldPasportNumber.getText().equals("") ||
                    textFieldIssuedBy.getText().equals("") || formattedTextFieldDateOfIssue.getText().equals("")){
                JOptionPane.showMessageDialog(frame,"Необходимо заполнить все поля","ВНИМАНИЕ",JOptionPane.WARNING_MESSAGE);
            } else{    
                if(db.sendInsert("INSERT INTO medunica.clients (family,"
                        + " name,"
                        + " patronomic,"
                        + " date_birth,"
                        + " snils,"
                        + " gender,"
                        + " ipr,"
                        + " ipr_date,"
                        + " telephone,"
                        + " email,"
                        + " pasport_series,"
                        + " pasport_number,"
                        + " issued_by,"
                        + " date_of_issue,"
                        + " residence_address,"
                        + " permanent_registration,"
                        + " disability_group,"
                        + " cause_of_disability,"
                        + " disability_date,"
                        + " primary_violations,"
                        + " rehabilitation_facilities,"
                        + " place_of_work,"
                        + " welfare_level, "
                        + " education,"
                        + " marital_status,"
                        + " service_form,"
                        + " receipt_date,"
                        + " last_modified_date)"
                    + " VALUES('"+textFieldFamily.getText()
                    +"', '"+textFieldName.getText()
                    +"', '"+textFieldPatron.getText()
                    +"', '"+formattedTextFieldDateBirth.getText()
                    +"', '"+formattedTextFieldSnils.getText()
                    +"', '"+gender
                    +"', '"+textFieldIpr.getText()
                    +"', '"+formattedTextFieldIprData.getText()
                    +"', '"+formattedTextFieldTelephone.getText()
                    +"', '"+formattedTextFieldEmail.getText()
                    +"', '"+formattedTextFieldPasportSeries.getText()
                    +"', '"+formattedTextFieldPasportNumber.getText()
                    +"', '"+textFieldIssuedBy.getText()
                    +"', '"+formattedTextFieldDateOfIssue.getText()
                    +"', '"+textFieldResidenceAddress.getText()
                    +"', '"+textFieldPermanentRegistration.getText()
                    +"', '"+comboBoxDisabilityGroup.getSelectedItem()
                    +"', '"+textFieldCauseOfDisability.getText()
                    +"', '"+formattedTextFieldDisabilityDate.getText()
                    +"', '"+comboBoxPrimaryViolations.getSelectedItem()
                    +"', '"+comboBoxRehabilitationFacilities.getSelectedItem()
                    +"', '"+textFieldPlaceOfWork.getText()
                    +"', '"+comboBoxWelfareLavel.getSelectedItem()
                    +"', '"+comboBoxEducation.getSelectedItem()
                    +"', '"+comboBoxMaritalStatus.getSelectedItem()
                    +"','"+comboBoxServiceForm.getSelectedItem()
                    +"', '"+formattedTextFieldReceiptDate.getText()
                    +"', '"+dateFormat.format(cal.getTime()
                    )+"')")){
                    JOptionPane.showMessageDialog(frame,"Данные успешно добавлены","МЕДУНИЦА",JOptionPane.INFORMATION_MESSAGE);
                    clearTexField();
                } else {
                    JOptionPane.showMessageDialog(frame,"Ошибка отправки запроса","ОШИБКА",JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(frame,"Необходимо заполнить все поля","ОШИБКА",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void radioButtonGenderMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonGenderMActionPerformed
        
        radioButtonGenderG.setSelected(false);
    }//GEN-LAST:event_radioButtonGenderMActionPerformed

    private void radioButtonGenderGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonGenderGActionPerformed
        
        radioButtonGenderM.setSelected(false);
    }//GEN-LAST:event_radioButtonGenderGActionPerformed

    // Кнопа запуска календаря "Дата поступления"
    private void btnReceiptDateCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiptDateCalendarActionPerformed
        dateChooserDialogReceiptDate.showDialog(this);
        DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        Date cal = dateChooserDialogReceiptDate.getCurrent().getTime();
        formattedTextFieldReceiptDate.setText(dateFormat.format(cal.getTime()));
    }//GEN-LAST:event_btnReceiptDateCalendarActionPerformed

    // Кнопа запуска календаря "Дата рождения"
    private void btnDataBirthCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataBirthCalendarActionPerformed

        dateChooserDialogReceiptDate.showDialog(this);
        DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        Date cal = dateChooserDialogReceiptDate.getCurrent().getTime();
        formattedTextFieldDateBirth.setText(dateFormat.format(cal.getTime()));
    }//GEN-LAST:event_btnDataBirthCalendarActionPerformed

    // Кнопа запуска календаря "Дата разработки ИПР"
    private void btnIprDateCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIprDateCalendarActionPerformed
        
        dateChooserDialogReceiptDate.showDialog(this);
        DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        Date cal = dateChooserDialogReceiptDate.getCurrent().getTime();
        formattedTextFieldIprData.setText(dateFormat.format(cal.getTime()));
    }//GEN-LAST:event_btnIprDateCalendarActionPerformed

    // Кнопа запуска календаря "Дата установки инвалидности"
    private void btnDisabilityDateCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisabilityDateCalendarActionPerformed
        
        dateChooserDialogReceiptDate.showDialog(this);
        DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        Date cal = dateChooserDialogReceiptDate.getCurrent().getTime();
        formattedTextFieldDisabilityDate.setText(dateFormat.format(cal.getTime()));
    }//GEN-LAST:event_btnDisabilityDateCalendarActionPerformed

    // Кнопа запуска календаря "Дата выдачи паспорта"
    private void btnDateOfIssueCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateOfIssueCalendarActionPerformed
        
        dateChooserDialogReceiptDate.showDialog(this);
        DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        Date cal = dateChooserDialogReceiptDate.getCurrent().getTime();
        formattedTextFieldDateOfIssue.setText(dateFormat.format(cal.getTime()));
    }//GEN-LAST:event_btnDateOfIssueCalendarActionPerformed

    // Кнопа выписки
    private void btnDischargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDischargeActionPerformed

        dateChooserDialogReceiptDate.showDialog(this);
        DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        Date cal = dateChooserDialogReceiptDate.getCurrent().getTime();
        dateFormat.format(cal.getTime());
    }//GEN-LAST:event_btnDischargeActionPerformed

    private void btnDataBirthCalendar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataBirthCalendar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDataBirthCalendar1ActionPerformed

    // Очистка полей ввода данных
    private void clearTexField(){
        textFieldFamily.setText(""); textFieldName.setText(""); textFieldPatron.setText(""); formattedTextFieldDateBirth.setText(""); formattedTextFieldSnils.setText("");
        formattedTextFieldPasportSeries.setText(""); formattedTextFieldPasportNumber.setText(""); textFieldIssuedBy.setText(""); formattedTextFieldDateOfIssue.setText("");
        textFieldResidenceAddress.setText(""); textFieldPermanentRegistration.setText(""); textFieldIpr.setText(""); formattedTextFieldIprData.setText("");
        formattedTextFieldTelephone.setText(""); formattedTextFieldEmail.setText(""); textFieldCauseOfDisability.setText(""); formattedTextFieldDisabilityDate.setText("");
        textFieldPlaceOfWork.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataBirthCalendar;
    private javax.swing.JButton btnDataBirthCalendar1;
    private javax.swing.JButton btnDateOfIssueCalendar;
    private javax.swing.JButton btnDisabilityDateCalendar;
    private javax.swing.JButton btnDischarge;
    private javax.swing.JButton btnIprDateCalendar;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnReceiptDateCalendar;
    private javax.swing.JComboBox<String> comboBoxDisabilityGroup;
    private javax.swing.JComboBox<String> comboBoxEducation;
    private javax.swing.JComboBox<String> comboBoxIncomeMotherFather;
    private javax.swing.JComboBox<String> comboBoxMaritalStatus;
    private javax.swing.JComboBox<String> comboBoxPrimaryViolations;
    private javax.swing.JComboBox<String> comboBoxRehabilitationFacilities;
    private javax.swing.JComboBox<String> comboBoxServiceForm;
    private javax.swing.JComboBox<String> comboBoxSpousesIncome12Months;
    private javax.swing.JComboBox<String> comboBoxWelfareLavel;
    private datechooser.beans.DateChooserDialog dateChooserDialogReceiptDate;
    private javax.swing.JFormattedTextField formattedTextField75pRecipientIncome;
    private javax.swing.JFormattedTextField formattedTextFieldActualContractAmount;
    private javax.swing.JFormattedTextField formattedTextFieldActualNumberDays;
    private javax.swing.JFormattedTextField formattedTextFieldAmountIncomeAllFamily;
    private javax.swing.JFormattedTextField formattedTextFieldAverageRevenue;
    private javax.swing.JFormattedTextField formattedTextFieldCapPerCapitaIncome;
    private javax.swing.JFormattedTextField formattedTextFieldContract24Days;
    private javax.swing.JFormattedTextField formattedTextFieldDateBirth;
    private javax.swing.JFormattedTextField formattedTextFieldDateOfIssue;
    private javax.swing.JFormattedTextField formattedTextFieldDifferencePerCapitaIncome;
    private javax.swing.JFormattedTextField formattedTextFieldDisabilityDate;
    private javax.swing.JFormattedTextField formattedTextFieldEmail;
    private javax.swing.JFormattedTextField formattedTextFieldIncomeMotherFather;
    private javax.swing.JFormattedTextField formattedTextFieldIncomeMotherFather1;
    private javax.swing.JFormattedTextField formattedTextFieldIprData;
    private javax.swing.JFormattedTextField formattedTextFieldNumberDaysMonth;
    private javax.swing.JFormattedTextField formattedTextFieldPasportNumber;
    private javax.swing.JFormattedTextField formattedTextFieldPasportSeries;
    private javax.swing.JFormattedTextField formattedTextFieldReceiptDate;
    private javax.swing.JFormattedTextField formattedTextFieldRecipientIncome12Months;
    private javax.swing.JFormattedTextField formattedTextFieldRecipientsPerCapitaIncome;
    private javax.swing.JFormattedTextField formattedTextFieldSnils;
    private javax.swing.JFormattedTextField formattedTextFieldSpousesIncome12Months;
    private javax.swing.JFormattedTextField formattedTextFieldSpousesIncome12Months1;
    private javax.swing.JFormattedTextField formattedTextFieldTelephone;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lbl75pRecipientIncome;
    private javax.swing.JLabel lblActualContractAmount;
    private javax.swing.JLabel lblActualNumberDays;
    private javax.swing.JLabel lblAmountIncomeAllFamily;
    private javax.swing.JLabel lblAverageRevenue;
    private javax.swing.JLabel lblCapPerCapitaIncome;
    private javax.swing.JLabel lblCauseOfDisability;
    private javax.swing.JLabel lblContract24Days;
    private javax.swing.JLabel lblDataBirth;
    private javax.swing.JLabel lblDateOfIssue;
    private javax.swing.JLabel lblDifferencePerCapitaIncome;
    private javax.swing.JLabel lblDisabilityDate;
    private javax.swing.JLabel lblDisabilityGroup;
    private javax.swing.JLabel lblEducation;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFamily;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblIncomeMotherFather;
    private javax.swing.JLabel lblIpr;
    private javax.swing.JLabel lblIprData;
    private javax.swing.JLabel lblIssuedBy;
    private javax.swing.JLabel lblMaritalStatus;
    private javax.swing.JLabel lblNamberOfFamily;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumberDaysMonth;
    private javax.swing.JLabel lblNumberMinorChildren;
    private javax.swing.JLabel lblPasportNumber;
    private javax.swing.JLabel lblPasportSeries;
    private javax.swing.JLabel lblPatron;
    private javax.swing.JLabel lblPermanentRegistration;
    private javax.swing.JLabel lblPlaceOfWork;
    private javax.swing.JLabel lblPrimaryViolations;
    private javax.swing.JLabel lblReceiptDate;
    private javax.swing.JLabel lblRecipientIncome12Months;
    private javax.swing.JLabel lblRecipientsPerCapitaIncome;
    private javax.swing.JLabel lblRehabilitationFacilities;
    private javax.swing.JLabel lblResidenceAddress;
    private javax.swing.JLabel lblServiseForm;
    private javax.swing.JLabel lblSnils;
    private javax.swing.JLabel lblSpousesIncome12Months;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JLabel lblWelfareLavel;
    private javax.swing.JPanel panelGeneralInformation;
    private javax.swing.JPanel panelSocialCharacteristic;
    private javax.swing.JRadioButton radioButtonGenderG;
    private javax.swing.JRadioButton radioButtonGenderM;
    private javax.swing.JSpinner spinnerNumberMinorChildren;
    private javax.swing.JTabbedPane tabbedPaneRegistrator;
    private javax.swing.JTextField textFieldCauseOfDisability;
    private javax.swing.JTextField textFieldFamily;
    private javax.swing.JTextField textFieldIpr;
    private javax.swing.JTextField textFieldIssuedBy;
    private javax.swing.JTextField textFieldName;
    private javax.swing.JTextField textFieldPatron;
    private javax.swing.JTextField textFieldPermanentRegistration;
    private javax.swing.JTextField textFieldPlaceOfWork;
    private javax.swing.JTextField textFieldResidenceAddress;
    // End of variables declaration//GEN-END:variables
}
